
server:
  port: 8990
  servlet:
    context-path: /
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #??Eureka????
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/ #Eureka Server??
  instance:
    prefer-ip-address: true


